#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

for arg; do case $arg in
    -parallel)          parallel=0;;
	-parallel_cont)     parallel_cont=0;;
    -ZND)               ZND=0;;
    *)                  echo "Unknown option '$arg'."; exit 1;;
esac; done

runApplication blockMesh
restore0Dir

if [[ "$ZND" ]]; then
    runApplication setZNDsolution
else
    # runApplication setFields
	echo "No ZND"
fi

if [[ "$parallel" ]]; then
	if [[ "$parallel_cont" ]]; then
		echo "Continuing parallel computation"
	else
	    runApplication decomposePar
	fi
    runParallel $application
    runApplication reconstructPar
else
    runApplication $application
fi

# ----------------------------------------------------------------- end-of-file
